import React from 'react';
import style from './Card.module.css';

export default function Card({notedata}) {
    const dataCard = [
        { title: 'Atomic Habit Summary', content: '        Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione' },
        { title: 'Atomic Habit Summary', content: '   Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostr Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus rationeum nam qui possimus necessitatibus ratione     Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione' },
        { title: 'Atomic Habit Summary', content: '   Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostr Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus rationeum nam qui possimus necessitatibus ratione     Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione' },
        { title: 'Atomic Habit Summary', content: '   Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostr Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus rationeum nam qui possimus necessitatibus ratione     Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione' },
        { title: 'Atomic Habit Summary', content: '   Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostr Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus rationeum nam qui possimus necessitatibus ratione     Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione' },
        { title: 'Atomic Habit Summary', content: '   Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostr Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus rationeum nam qui possimus necessitatibus ratione     Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione' },
        { title: 'Atomic Habit Summary', content: '   Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostr Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus rationeum nam qui possimus necessitatibus ratione     Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione' },
        { title: 'Atomic Habit Summary', content: '   Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostr Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus rationeum nam qui possimus necessitatibus ratione     Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione' },
        { title: 'Atomic Habit Summary', content: '   Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostr Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus rationeum nam qui possimus necessitatibus ratione     Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione' },
        { title: 'Atomic Habit Summary', content: '   Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostr Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus rationeum nam qui possimus necessitatibus ratione     Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione' },
        { title: 'Atomic Habit Summary', content: '   Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostr Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus rationeum nam qui possimus necessitatibus ratione     Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione' },
        { title: 'Atomic Habit Summary', content: '   Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostr Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus rationeum nam qui possimus necessitatibus ratione     Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quam non hic quo id, nostrum nam qui possimus necessitatibus ratione' },


    ]
    return (
        <>
            <div className={style.cardParent}>

                {notedata.map((item) => (
                    <div className={style.cardData} key={item.id}>
                        <h3>{item.title}</h3>
                        <p>{item.content}</p>
                    </div>
                ))}

            </div>
        </>
    );
}